
[build]
  command = "yarn run build"
  functions = ".next/serverless/pages"
  publish = ".next/serverless/pages"

# Uncomment to use this redirect for Single Page Applications. 
# Not needed for static site generators.
[[redirects]]
 from = "/*"
 to = "/.netlify/functions/:splat"
 status = 200